# Generated by Django 5.1.3 on 2024-11-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_article_id_alter_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_post',
        ),
    ]
