# Generated by Django 5.1.3 on 2024-11-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_comment_commented_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='api.article'),
            preserve_default=False,
        ),
    ]
