# Generated by Django 5.1.3 on 2024-12-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_item_name_shopitem_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitem',
            old_name='title',
            new_name='item_name',
        ),
    ]
