# Generated by Django 5.1.3 on 2024-12-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buy_item_name', to='api.shopitem'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
