# Generated by Django 5.1.3 on 2024-12-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_salesorder_item_salesorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_item_name', to='api.shopitem'),
        ),
    ]
