# Generated by Django 5.1.3 on 2024-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_salesorder_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
