# Generated by Django 5.1.3 on 2024-12-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_salesorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(default='กำลังเตรียมสินค้า', max_length=50),
        ),
    ]
