# Generated by Django 5.1.3 on 2024-12-15 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
